USE uzalendo_chama;

-- Chama
INSERT INTO chamas (name, description)
VALUES (
    'Uzalendo Chama Investment Group',
    'A registered Chama savings and investment group in Kenya'
);

-- Admin (Treasurer)
-- Password hash is a placeholder. Real hash generated by bcrypt in Phase 4.
INSERT INTO admins (chama_id, full_name, email, phone, password_hash)
VALUES (
    1,
    'Treasurer Admin',
    'treasurer@uzalendo.co.ke',
    '0700000001',
    'placeholder_hash'
);

-- Members (status PENDING — admin must activate)
INSERT INTO members (chama_id, full_name, phone, national_id, member_number, password_hash, status, loan_limit)
VALUES
(1, 'Graffin Obae',  '0711111111', '12345678', 'UZA001', 'placeholder_hash', 'PENDING', 0.00),
(1, 'Jane Mwangi',   '0722222222', '23456789', 'UZA002', 'placeholder_hash', 'PENDING', 0.00),
(1, 'Peter Otieno',  '0733333333', '34567890', 'UZA003', 'placeholder_hash', 'PENDING', 0.00);

-- Member scores (one per member, starts at 50)
INSERT INTO member_scores (member_id)
VALUES (1), (2), (3);

-- Audit log of admin activating members
INSERT INTO audit_logs (performed_by_admin, action, target_table, target_id, details)
VALUES
(1, 'MEMBER_REGISTERED', 'members', 1, 'Member UZA001 registered and pending activation'),
(1, 'MEMBER_REGISTERED', 'members', 2, 'Member UZA002 registered and pending activation'),
(1, 'MEMBER_REGISTERED', 'members', 3, 'Member UZA003 registered and pending activation');